name: Build docker images

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build back
        uses: docker/build-push-action@v2
        with:
          context: ./back/
          push: true
          tags: whitespots/security-requirements-generator-back:0.1.0
      -
        name: Build front
        uses: docker/build-push-action@v2
        with:
          context: ./front/
          push: true
          tags: whitespots/security-requirements-generator-front:0.1.0
      -
        name: Build nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx/
          push: true
          tags: whitespots/security-requirements-generator-nginx:0.1.0
